on: 
  push:
    branches:
    - blobtoregistry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - name: Checkout the branch code
      uses: actions/checkout@v2
      with:
        ref: blobtoregistry

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Deploy Bicep files
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: storagePrefix=bicepdemo
        failOnStdErr: false