name: DeployServiceBusToACR
on: 
  push:
    paths:
      - 'servicebus/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.31.0
        inlineScript: |
          ls -la $GITHUB_WORKSPACE
          az bicep install
          az bicep publish --file $GITHUB_WORKSPACE/servicebus/servicebus.bicep --target br:bicepmodule.azurecr.io/servicebus/servicebus:v1
          